LINUX_OVERRIDE_SRCDIR = ../linux-fsimx7ulp/
LINUX_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = --include .git
UBOOT_OVERRIDE_SRCDIR = ../u-boot-fsimx7ulp/
UBOOT_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = --include .git

