#!/bin/sh

TARGET="$1"
COMMON=board/f+s/common
BOARD=board/f+s/PicoMOD7A
CP="/bin/cp -f"

tput smso
echo ">>>   Doing final F+S PicoMOD7A setup for minimal configuration"
tput rmso

# Call common F+S setup for standard configuration
sh ./${COMMON}/final_script_min ${TARGET} ${BOARD}
