LINUX_OVERRIDE_SRCDIR = ../linux-fsimx8mm/
LINUX_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = --include .git
UBOOT_OVERRIDE_SRCDIR = ../u-boot-fsimx8mm/
UBOOT_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = --include .git

