#!/bin/sh

COMMON=board/f+s/common
FS_ARCH=fsimx8mp
USE_G2D=1

# Source-in common F+S setup for standard configuration
. $COMMON/finalscript_std-common

# Install rules to create /dev/input/touchscreen[0..] device
mkdir -p ${TARGET}/etc/udev/rules.d
${CP} ${COMMON}/etc/udev/rules.d/touchscreen.rules ${TARGET}/etc/udev/rules.d
