LINUX_OVERRIDE_SRCDIR = ../linux-fsimx8mp/
LINUX_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = --include .git
UBOOT_OVERRIDE_SRCDIR = ../u-boot-fsimx8mp/
UBOOT_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = --include .git

