#!/bin/sh

TARGET="$1"
COMMON=board/f+s/common
BOARD=board/f+s/QBlissA9
CP="/bin/cp -f"

tput smso
echo ">>>   Doing final F+S QBlissA9 setup for standard configuration"
tput rmso

# Call common F+S setup for standard configuration
sh ./${COMMON}/final_script_std ${TARGET} ${BOARD}
