#!/bin/sh

TARGET="$1"
COMMON=board/f+s/common
BOARD=board/f+s/fsimx6
CP="/bin/cp -f"

tput smso
echo ">>>   Doing final F+S iMX6 setup for standard configuration"
tput rmso

${CP} ./${COMMON}/.xinitrc ./system/skeleton/root/
# Call common F+S setup for standard configuration
sh ./${COMMON}/final_script_std ${TARGET} ${BOARD}
#inittab is copied by final_script in common-directory
#${CP} ${BOARD}/inittab ${TARGET}/etc
#${CP} ${COMMON}/etc/inittab ${TARGET}/etc
