#!/bin/sh

TARGET="$1"
COMMON=board/f+s/common
BOARD=board/f+s/fss5pv210

tput smso
echo ">>>   Doing final fss5pv210 setup for minimal configuration"
tput rmso

# Call common F+S setup for minimal configuration
sh ./${COMMON}/final_script_min ${TARGET} ${BOARD}
