#!/bin/sh

COMMON=board/f+s/common
FS_ARCH=fss5pv210
INITTAB=$COMMON/etc/inittab-$FS_ARCH

# Source-in the common F+S setup for standard configuration
. ${COMMON}/finalscript_std-common

# Copy the hdmicfg script and startup script
${CP} ${COMMON}/hdmicfg ${TARGET}/sbin
${CP} ${COMMON}/etc/init.d/S17hdmicfg ${TARGET}/etc/init.d
