#!/bin/sh

TARGET="$1"
BOARD="$2"
COMMON=board/f+s/common
CP="/bin/cp -f"

tput smso
echo ">>>   Doing final F+S (common) setup for HDMI configuration"
tput rmso

# Copy the hdmicfg script and startup script
${CP} ${COMMON}/hdmicfg ${TARGET}/sbin
${CP} ${COMMON}/etc/init.d/S17hdmicfg ${TARGET}/etc/init.d
