#!/bin/sh

TARGET="$1"
BOARD="$2"
COMMON=board/f+s/common
CP="/bin/cp -f"

# Copy the modified inittab file with mdev support
${CP} ${COMMON}/inittab ${TARGET}/etc

# Copy the modified profile file with display and xauth exports
${CP} ${COMMON}/profile ${TARGET}/etc

# Copy the enhanced mdev configuration file
${CP} ${COMMON}/mdev.conf ${TARGET}/etc

# Copy the start script to set up the F&S environment
${CP} ${COMMON}/S01fssetup ${TARGET}/etc/init.d

# Copy the x11 start script
${CP} ${COMMON}/S35x11 ${TARGET}/etc/init.d

# Copy the x11 configuration file
mkdir -p ${TARGET}/etc/X11
${CP} ${COMMON}/xorg.conf ${TARGET}/etc/X11

# setup touch controller configuration
mkdir -p ${TARGET}/etc/profile.d
${CP} ${COMMON}/tslib.sh ${TARGET}/etc/profile.d

# Newer toolchains create ld-linux-armhf.so.3, but we also need ld-linux.so.3
if [ -L "${TARGET}/lib/ld-linux-armhf.so.3" ] && [ ! -e "${TARGET}/lib/ld-linux.so.3" ];
then
    ld=`readlink ${TARGET}/lib/ld-linux-armhf.so.3`
    ln -s "${ld}" ${TARGET}/lib/ld-linux.so.3
fi
