#!/bin/sh

TARGET="$1"
BOARD="$2"
LOCAL=board/f+s/common
CP="/bin/cp -f"

tput smso
echo ">>>   Doing final F+S (common) setup for minimal configuraton"
tput rmso

# Copy the modified inittab file with mdev support
${CP} ${BOARD}/inittab ${TARGET}/etc

# Copy the enhanced mdev configuration file
${CP} ${LOCAL}/mdev.conf ${TARGET}/etc
