#!/bin/sh
#
# This file is meant to be sourced in by the final script of a board. The
# calling script can set the following variables. If a variable is not set,
# the default in parentheses is used.
#
#   XORG_CONF: Path of the xorg.conf file to use ($COMMON/etc/X11/xorg.conf)
#
# The script sources in the common_min_final script, which means all variables
# described there can also be used.
#

# Source-in the minimal setup as this is a subset of our task
FS_CONFIG=${FS_CONFIG:-standard}
. board/f+s/common/finalscript_min-common

XORG_CONF=${XORG_CONF:-$COMMON/etc/X11/xorg.conf}

#XORG_CONF_D=etc/X11/xorg.conf.d
XORG_CONF_D=usr/share/X11/xorg.conf.d

# setup touch controller configuration
mkdir -p ${TARGET}/etc/profile.d
${CP} ${COMMON}/etc/profile.d/tslib.sh ${TARGET}/etc/profile.d
# setup sound configuration
mkdir -p ${TARGET}/var/lib/alsa
${CP} ${COMMON}/var/lib/alsa/asound.state ${TARGET}/var/lib/alsa
${CP} ${COMMON}/etc/asound.conf ${TARGET}/etc

# Install wpa_supplicant.conf with country=DE
install -m 0664 ${COMMON}/etc/wpa_supplicant.conf ${TARGET}/etc/

# Copy the weston start script
if grep ^BR2_PACKAGE_WESTON=y $BR2_CONFIG > /dev/null; then
    # Copy start script for weston client
    ${CP} ${COMMON}/etc/init.d/S40weston ${TARGET}/etc/init.d
    # Setup weston environment
    mkdir -p ${TARGET}/etc/profile.d
    ${CP} ${COMMON}/etc/profile.d/weston.sh ${TARGET}/etc/profile.d
    # Install weston.ini
    mkdir -p ${TARGET}/etc/xdg/weston
    ${CP} ${COMMON}/etc/xdg/weston/weston.ini ${TARGET}/etc/xdg/weston

	if [ $USE_G2D -eq 1 ];then
		sed -i 's/#use-g2d=1/use-g2d=1/g' ${TARGET}/etc/xdg/weston/weston.ini
	fi
	# Activate xwayland if XSERVER is installed
	if grep ^BR2_PACKAGE_WESTON_XWAYLAND=y $BR2_CONFIG > /dev/null; then
	    # Copy enhanced profile (with DISPLAY and XAUTHORITY)
	    ${CP} ${COMMON}/etc/profile.d/xserver.sh ${TARGET}/etc/profile.d
		sed -i 's/#xwayland=true/xwayland=true/g' ${TARGET}/etc/xdg/weston/weston.ini
	fi
	install -m 0664 ${COMMON}/etc/udev/rules.d/SX8654-touchscreen.rules ${TARGET}/etc/udev/rules.d/
	install -m 0664 ${COMMON}/etc/udev/rules.d/TSC2004-touchscreen.rules ${TARGET}/etc/udev/rules.d/
fi

if grep ^BR2_PACKAGE_FS_UPDATE_SOLUTION=y $BR2_CONFIG > /dev/null; then
	${CP} ${COMMON}/sbin/preinit.sh ${TARGET}/sbin/preinit.sh

	mkdir -p ${TARGET}/rw_fs/root/application/current

	${CP} ${COMMON}/dynamic_mounting.py ${TARGET_DIR}/rw_fs/

	${CP} ${COMMON}/etc/fw_version ${TARGET}/etc/

	mkdir -p ${TARGET}/etc/rauc
    mkdir -p ${TARGET}/mnt/rauc/bundle

	${CP} ${COMMON}/rauc/rauc.cert.pem ${TARGET}/etc/rauc

	install -m 0444 ${COMMON}/etc/udev/rules.d/99-fus-updater-usb-auto-mount.rules ${TARGET}/etc/udev/rules.d/
	install -m 0444 ${COMMON}/usr/libexec/usb_fs_updater.sh ${TARGET}/usr/libexec/usb_fs_updater.sh
	install -m 0555 ${COMMON}/sbin/preinit.sh ${TARGET}/sbin

	if grep	^BR2_PACKAGE_FS_UPDATE_SOLUTION_NAND=y $BR2_CONFIG > /dev/null; then
		${CP}  ${COMMON}/etc/rauc/system.conf.nand ${TARGET}/etc/rauc/system.conf
		${CP}  ${COMMON}/etc/fw_env.config.nand ${TARGET}/etc/fw_env.config
	elif grep ^BR2_PACKAGE_FS_UPDATE_SOLUTION_MMC=y $BR2_CONFIG > /dev/null; then
		${CP}  ${COMMON}/etc/rauc/system.conf.mmc ${TARGET}/etc/rauc/system.conf
		${CP}  ${COMMON}/etc/fw_env.config.mmc ${TARGET}/etc/fw_env.config
	fi
fi
