#!/bin/sh
# Set up F&S environment

login_tty=/dev/login_tty

dostart=0
dostop=0

case "$1" in
    start)
	dostart=1
	;;
    stop)
	dostop=1
	;;
    restart|reload)
	dostop=1
	dostart=1
	;;
    *)
	echo $"Usage: $0 {start|stop|restart}"
esac

if [ ${dostop} -ne 0 ] ; then
    echo "Removing F&S environment..."

    # Remove symbolic link from login_tty
    if [ -L ${login_tty} ] ; then
	/bin/rm ${login_tty}
    fi
fi

if [ ${dostart} -ne 0 ] ; then
    echo "Setting up F&S environment..."

    # Create a symbolic link from login_tty to the first console listed in
    # /proc/consoles. The F&S inittab starts a getty on login_tty.
    con=`head -n 1 /proc/consoles | cut -f 1 -d ' '`
    if [ "x${con}" != "x" ] ; then
	ln -s /dev/${con} ${login_tty}
    fi
fi
