LINUX_OVERRIDE_SRCDIR = ../linux-fsimx6sx/
LINUX_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = --include .git
UBOOT_OVERRIDE_SRCDIR = ../u-boot-fsimx6sx/
UBOOT_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = --include .git

