#!/bin/sh
# Start CUBEA5 environment

login_tty=/dev/login_tty

dostart=0
dostop=0

case "$1" in
    start)
	dostart=1
	;;
    stop)
	dostop=1
	;;
    restart|reload)
	dostop=1
	dostart=1
	;;
    *)
	echo $"Usage: $0 {start|stop|restart}"
esac

if [ ${dostop} -ne 0 ] ; then
    # Remount export and data volumes read-only
    mount -o remount,ro /data
    mount -o remount,ro /export

    # Remove symbolic link from login_tty
    if [ -L ${login_tty} ] ; then
	/bin/rm ${login_tty}
    fi
    echo "CUBEA5 environment stopped"
fi

if [ ${dostart} -ne 0 ] ; then
    # Remount export and data volumes read-write
    mount -o remount,rw /export
    mount -o remount,rw /data

    # Remove update.scr or it will be triggered again on next boot
    /bin/rm -f /data/update.scr

    if [ -e /sys/bdinfo/login_tty ] ; then
	con=$(cat /sys/bdinfo/login_tty)
	ln -s /dev/${con} ${login_tty}
    fi
    echo "CUBEA5 environment started"
fi
