#!/bin/sh
# Set up F&S environment

login_tty=/dev/login_tty

dostart=0
dostop=0

case "$1" in
    start)
	dostart=1
	;;
    stop)
	dostop=1
	;;
    restart|reload)
	dostop=1
	dostart=1
	;;
    *)
	echo $"Usage: $0 {start|stop|restart}"
esac

if [ ${dostop} -ne 0 ] ; then
    # Remove symbolic link from login_tty
    if [ -L ${login_tty} ] ; then
	/bin/rm ${login_tty}
    fi
    echo "F&S environment stopped"
fi

if [ ${dostart} -ne 0 ] ; then
    if [ -e /sys/bdinfo/login_tty ] ; then
	con=$(cat /sys/bdinfo/login_tty)
	ln -s /dev/${con} ${login_tty}
    fi
    echo "F&S environment started"
fi
