#!/bin/sh
# Generic post-install script

login_tty=/dev/login_tty
default_tty=ttymxc3

dostart=0
dostop=0

case "$1" in
    start)
        dostart=1
        ;;
    stop)
        dostop=1
        ;;
    restart|reload)
        dostop=1
        dostart=1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
esac

if [[ ${dostop} -ne 0 ]] ; then
	echo "RAUC service stops"
	start-stop-daemon -K -q -p /var/run/rauc.pid
	if [[ $? = 0 ]] ; then
		echo "OK"
	else
		echo "FAIL"
	fi
fi

if [[ ${dostart} -ne 0 ]] ; then

    #Update U-Boot ENV
    if [[ "$(fw_printenv -n BOOT_ORDER)" != "$(fw_printenv -n BOOT_ORDER_ALT)" ]]; then
            echo "RAUC Post-Install Script!"
            if [[ "$(fw_printenv -n BOOT_B_LEFT)" == "0" ]] || [[ "$(fw_printenv -n BOOT_A_LEFT)" == "0" ]]; then
                    fw_setenv BOOT_ORDER $(fw_printenv -n BOOT_ORDER_ALT)
                    echo "Update wasn't successfull"
            else
                    fw_setenv BOOT_ORDER_ALT $(fw_printenv -n BOOT_ORDER)
                    echo "Update was successfull"
            fi;
	else
		echo "Nothing to do"
    fi;

fi


