#!/bin/sh
# Start X server and matchbox window manager
#
pid_file=/var/run/X11.pid
log_file=/var/log/startx.log
tsconf_file=/var/run/tslib.conf

case "$1" in
    start)
	echo "Starting X and matchbox WM..."
	inputdev=default-event0
	tslibdev=/dev/input/event0
	sysevent=/sys/class/input/event0
	for i in /sys/class/input/event*
	do
            if [ "`cat $i/device/name`" = "Atmel maXTouch Touchscreen" ] || [ "`cat $i/device/name`" = "ft5x0x_ts" ]
            then
		inputdev=cap-`basename $i`
		tslibdev=/dev/input/`basename $i`
		sysevent=$i
		break
            fi
	done
	echo "Configure input for: $inputdev " `cat $sysevent/device/name`
	echo "#!/bin/sh" >$tsconf_file
	echo "export TSLIB_TSDEVICE=$tslibdev" >>$tsconf_file
	echo "export TSLIB_CALIBFILE=/etc/pointercal-$inputdev" >>$tsconf_file
	. $tsconf_file
	/usr/bin/startx /usr/bin/matchbox-session > $log_file 2> $log_file -- -pointer $inputdev&
#start-stop-daemon --start --pidfile $pid_file --make-pidfile --name dkstartx --startas /usr/bin/startx /usr/bin/matchbox-session > $log_file 2> $log_file -- -- -pointer $inputdev &
	;;
    stop|restart|reload)
	#echo "Can't stop X server! No info about PID."
	#start-stop-daemon --stop --pidfile $pid_file
	PS_XINIT=`ps | grep xinit`
	set -- $PS_XINIT
	PID=$1
	kill $PID
	;;
    *)
	echo $"Usage: $0 {start|stop|restart}"
esac
