#!/bin/sh
# Start weston client
#

architecture=$(cat /sys/bdinfo/arch)

case "$1" in
    start)
	echo "Starting Weston..."

	# Create folder and setup access privileges
	mkdir -p /var/run/weston
	chmod 0700 /var/run/weston

	# Setup environment variable
	source /etc/profile.d/weston.sh

	# Start weston client
	if [ "$architecture" == "fsimx6ul" ] ; then
		start-stop-daemon -S -q -m -b -p /var/run/weston.pid \
		-x /usr/bin/weston -- --backend=fbdev-backend.so \
		--tty=1 --device=/dev/fb0 --log=/var/log/weston.log
	else
		start-stop-daemon -S -q -m -b -p /var/run/weston.pid \
		-x /usr/bin/weston -- --backend=fbdev-backend.so --use-g2d=1 \
		--tty=1 --device=/dev/fb0 --log=/var/log/weston.log
	fi
	;;

    stop)
	echo "Stopping Weston..."

	# Setup environment variable
	source /etc/profile.d/weston.sh

	# Stop weston client
	if [ "$architecture" == "fsimx6ul" ] ; then
		start-stop-daemon -K -q -m -b -p /var/run/weston.pid \
		-x /usr/bin/weston -- --backend=fbdev-backend.so \
		--tty=1 --device=/dev/fb0 --log=/var/log/weston.log
	else
		start-stop-daemon -K -q -m -b -p /var/run/weston.pid \
		-x /usr/bin/weston -- --backend=fbdev-backend.so --use-g2d=1 \
		--tty=1 --device=/dev/fb0 --log=/var/log/weston.log
	fi
	;;

    restart|reload)
	# Simply stop and start the service
	$0 stop
	$0 start
	;;

    *)
	echo $"Usage: $0 {start|stop|restart}"
	;;
esac
