#!/bin/sh
# Start weston client
#

architecture=$(cat /sys/bdinfo/arch)

case "$1" in
    start)
	echo "Starting Weston..."

	# Create folder and setup access privileges
	mkdir -p /var/run/weston
	chmod 0700 /var/run/weston
    if grep ^xwayland=true /etc/xdg/weston/weston.ini > /dev/null; then
        mkdir -p /tmp/.X11-unix/
		# Remove DISPLAY environment variable or else weston will try to start with X11 backend
		unset DISPLAY
    fi
	# Setup environment variable
	source /etc/profile.d/weston.sh

	# Start weston client
	start-stop-daemon -S -q -m -b -p /var/run/weston.pid \
	-x /usr/bin/weston -- --tty=1 --log=/var/log/weston.log

	# We need to set the X11 environment variables AFTER weston is started
	# or else weston will try to start with X11 backend
    if grep ^xwayland=true /etc/xdg/weston/weston.ini > /dev/null; then
		source /etc/profile.d/xserver.sh
    fi

	;;

    stop)
	echo "Stopping Weston..."

	# Setup environment variable
	source /etc/profile.d/weston.sh

	# Stop weston client
	start-stop-daemon -K -q -m -b -p /var/run/weston.pid \
	-x /usr/bin/weston -- --tty=1 --log=/var/log/weston.log
	;;

    restart|reload)
	# Simply stop and start the service
	$0 stop
	sleep 1
	$0 start
	;;

    *)
	echo $"Usage: $0 {start|stop|restart}"
	;;
esac
